FROM nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04


ENV CUDA_PKG_VERSION=10-2=10.2.130-1
ENV CUDA_VERSION=10.2.130
ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda-10.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_REQUIRE_CUDA=cuda>=10.2 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411
ENV NCCL_VERSION=2.4.8
ENV CUDNN_VERSION=7.6.5.32

COPY src/main /main

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  locales \
  software-properties-common \
  python3-pip python3-dev \
    cuda-command-line-tools-10-2 \
  cuda-cufft-10-2 \
  cuda-curand-10-2 \
  cuda-cusolver-10-2 \
  cuda-cusparse-10-2 
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y install python-opencv
RUN pip3 install --upgrade pip


RUN pip3 install  Pillow \
  		  pytest \
  		# fastapi dependencies
  		  fastapi[all] \
  		# project dependencies
  	  	  numpy \
		  gluoncv \
		  opencv-python
RUN pip3 install jsonschema
RUN pip3 install mxnet-cu102mkl
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 
COPY /gluoncv /usr/local/lib/python3.6/dist-packages/gluoncv 

WORKDIR /main
    
CMD ["uvicorn", "start:app", "--host", "0.0.0.0", "--port", "4343"]
